// Code generated by "stringer -type ProtoCode -linecomment"; DO NOT EDIT.

package protocode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error - -1]
	_ = x[Account_Create-1000]
	_ = x[Account_Auth-1001]
}

const (
	_ProtoCode_name_0 = "Error"
	_ProtoCode_name_1 = "Account_CreateAccount_Auth"
)

var (
	_ProtoCode_index_1 = [...]uint8{0, 14, 26}
)

func (i ProtoCode) String() string {
	switch {
	case i == -1:
		return _ProtoCode_name_0
	case 1000 <= i && i <= 1001:
		i -= 1000
		return _ProtoCode_name_1[_ProtoCode_index_1[i]:_ProtoCode_index_1[i+1]]
	default:
		return "ProtoCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
